# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.6.2
      with:
        # Directory to install Qt
        dir: c:/Qt # optional
        # Version of Qt to install
        version: 5.12.5 # optional, default is 5.12.8
        # Architecture for Windows/Android
        arch: Windows # optional
        # Whether or not to install Qt dependencies on Linux
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
      
    - name: Build something requiring CL.EXE
      run: |
        cmake -G "NMake Makefiles" .
        nmake
